fix(minio): create bucket error

diff --git a/rootfs/bin/create_bucket b/rootfs/bin/create_bucket
--- a/rootfs/bin/create_bucket
+++ b/rootfs/bin/create_bucket
@@ -4,7 +4,16 @@ set -e
 
 # shellcheck disable=SC1091
 source /bin/normalize_storage
-has_bucket=$(mc ls minio -json|jq -r '.key'|grep -w "${MINIO_BUCKET}")
-if  [ -z "$has_bucket" ] ;then
+
+has_bucket(){
+    mc ls minio -json|jq -r '.key'|grep -w "${MINIO_BUCKET}"
+}
+
+if  [ -z "$(has_bucket)" ] ;then
     mc mb minio/"${MINIO_BUCKET}"
+    if  [ -z "$(has_bucket)" ] ;then
+        echo "create bucket ${MINIO_BUCKET} error"
+        exit 1
+    fi
 fi
+echo "create bucket ${MINIO_BUCKET} success"
